#!/bin/bash
######################################################################################
#                          ZPX-GET  FOR ZPANEL FR Team Installer                     #
#                   Created by : andykimpe (andykimpe@gmail.com.com)                 #
#               Current maintainer : andykimpe (andykimpe@gmail.com.com)             #
#  Licensed Under the GPL3 (https://github.com/ZPanelFR/zpx-get/blob/master/LICENSE) #
#                                      Version 1.0.0                                 #
######################################################################################
if [ -f /usr/bin/apt-get ]
then
zpx=apt-get
elif [ -f /usr/bin/yum ]
then
zpx=yum
else
echo -e "###################################################################"
echo -e "#              you can not use zpx-get on your system              #"
echo -e "#"                                                                 #"
echo -e "# there may be in no installer zpanelx compatible for your system  #"
echo -e "#                                                                  #"
echo -e "####################################################################
exit 1
fi
$zpx $@
exit 0
#if [ $2 == upgrade ]
