#!/bin/bash
# apt-get or yum for zpanelx installer
if [ -f /usr/bin/apt-get ]
then
if [ "$1" == "upgrade" ]
then
UP1=dist-upgrade
UP2=$2
UP3=$3
elif [ "$2" == "upgrade" ]
then
UP1=$1
UP2=dist-upgrade
UP3=$3
elif [ "$3" == "upgrade" ]
then
UP1=$1
UP2=$2
UP3=dist-upgrade
else
UP1=$1
UP2=$2
UP3=$3
fi
apt-get -y $UP1 $UP2 $UP3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15
elif [ -f /usr/bin/yum ]
then
yum $1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15
else
echo -e "your systèm and not compatibility"
fi
